#!/usr/bin/env bash

usage() {
  printf "%s usage:\n" "$(basename "$0")"
  printf "\t-i SSH Key Path\n"
  printf "\t-u SSH user\n"
  printf "\t-H Trino Coordinator Hostname or IP\n"
  printf "\t-f Local path to save the coordinator certificate\n"
  printf "Make sure to check trino-setup for additional arguments\n"
}
# This is where the coordinator certificate will be saved locally
LOCAL_CERT="$(pwd)/trino-coordinator.crt"
SSH_USER="acceldata"

while getopts "u:i:f:H:h" arg; do
  case $arg in
    i) SSH_KEY=${OPTARG};;
    u) SSH_USER=${OPTARG};;
    H) HOST=${OPTARG};;
    f) LOCAL_CERT=${OPTARG};;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done
shift $((OPTIND - 1))


if [ -z "$SSH_KEY" ] || [ -z "$HOST" ] || [ -z "$SSH_USER" ]; then
  usage
  exit 1
fi

ssh -i "$SSH_KEY" "$SSH_USER@$HOST" bash -s -- "$@" < trino-setup
scp -i "$SSH_KEY" "$SSH_USER@$HOST:/tmp/trino.crt" "$LOCAL_CERT"
