#!/usr/bin/env bash

set -e

usage() {
  ACTUAL_PATH="$(realpath "$0")"
  PARENT_FOLDER="$(dirname "$ACTUAL_PATH")"
  printf "%s usage:\n" "$(basename "$0")"
  printf "\t-j JDK_HOME_PATH\n"
  printf "\t-p PASSWORD\n"
  printf "\t-c Trino certificate path\n"
  printf "\t-C Trino Coordinator certificate path\n"
  printf "\t-l JDK URL\n"
  printf "\t-t Trino user"
  printf "\t-k Trino keystore PATH (.jks)\n"
  printf "\t-r Java truststore password\n"
  printf "Make sure to import your Coordinator's .crt certificate on each of your worker hosts as well\n"
  if [ -f "$PARENT_FOLDER/workers.sh" ]; then
    printf "You can do this using the worker script found at %s/workers.sh\n" "$PARENT_FOLDER"
  fi
}

START_DIR="$(pwd)"
PASSWORD="Hadoop@123"
VALID_JAVA="23"
JAVA_HOME=/opt/jdk-"$VALID_JAVA"
COORDINATOR_CERT="/tmp/trino-coordinator.crt"
TRINO_KEYSTORE="/etc/trino/trino.jks"
TRUSTSTORE_PASSWORD="changeit"
CERT="/tmp/trino.crt"
# Whatever url this is, it needs to point directly to the tarball
JDK_URL="https://github.com/adoptium/temurin23-binaries/releases/download/jdk-23.0.2%2B7/OpenJDK23U-jdk_x64_linux_hotspot_23.0.2_7.tar.gz"
TRINO_USER="trino"

while getopts "p:j:c:C:l:t:k:r:h" arg; do
  case $arg in
  p) PASSWORD=${OPTARG} ;;
  j) JAVA_HOME=${OPTARG} ;;
  c) CERT=${OPTARG} ;;
  C) COORDINATOR_CERT=${OPTARG} ;;
  l) JDK_URL=${OPTARG} ;;
  t) TRINO_USER=${OPTARG} ;;
  k) TRINO_KEYSTORE=${OPTARG} ;;
  r) TRUSTSTORE_PASSWORD=${OPTARG} ;;
  h | *)
    usage
    exit 0
    ;;
  esac
done
shift $((OPTIND - 1))

if [ -z "$JAVA_HOME" ] || [ -z "$PASSWORD" ] || [ -z "$CERT" ] || [ -z "$JDK_URL" ]; then
  usage
  exit 1
fi

if [ ! -f /etc/os-release ]; then
  echo >&2 "This script should only be run on Linux, unless you know what you're doing."
  read -r -p "Continue anyway? (Y/N): " confirm && [[ "$confirm" == [yY] || "$confirm" == [yY][eE][sS] ]] || exit 1
fi

# This is so that this script can be run before Trino is installed
if ! grep "hadoop" /etc/group >/dev/null 2>&1; then
  sudo groupadd hadoop
fi

sudo useradd -m trino -G hadoop || echo "Trino user exists"
echo "$TRINO_USER:trino" | sudo chpasswd

if [ ! -d "$JAVA_HOME" ]; then
  sudo mkdir -p "$JAVA_HOME"
fi

if [ -f "$JAVA_HOME/bin/java" ]; then
  JAVA_VERSION="$("$JAVA_HOME/bin/java" -version 2>&1 | perl -ne 'print $1 if /["](\d{1,2})[0-9.]+["]/')"
  if [ "$JAVA_VERSION" -ne "$VALID_JAVA" ]; then
    printf >&2 "Existing JDK version '%s' in %s on $(hostname) is not supported\n" "$JAVA_VERSION" "$JAVA_HOME"
    exit 1
  fi
else
  cd "$(dirname "$JAVA_HOME")"
  echo "Downloading JDK-$VALID_JAVA..."
  sudo wget -q "$JDK_URL" -O jdk-$VALID_JAVA.tar.gz
  echo "Download complete!"

  sudo tar xf jdk-$VALID_JAVA.tar.gz -C "$JAVA_HOME" --strip-components 1
  sudo rm jdk-$VALID_JAVA.tar.gz
fi

if [ ! -d /etc/trino ]; then
  sudo mkdir -p /etc/trino/ && sudo chmod 770 /etc/trino/ && sudo chown -R "$TRINO_USER:hadoop" /etc/trino
fi

if [ ! -f "$JAVA_HOME/bin/keytool" ]; then
  echo "Cannot find keytool in JAVA_HOME='$JAVA_HOME'. Something is wrong."
  exit 1
fi

if [ ! -f "$JAVA_HOME/lib/security/cacerts" ]; then
  echo "Cannot find cacerts in JAVA_HOME='$JAVA_HOME'. Something is wrong."
  exit 1
fi

if sudo "$JAVA_HOME/bin/keytool" -list -keystore "$TRINO_KEYSTORE" -storepass "$PASSWORD" -alias trino >/dev/null 2>&1; then
  echo "Removing existing alias 'trino' from $TRINO_KEYSTORE"
  sudo "$JAVA_HOME/bin/keytool" -delete -alias trino -keystore "$TRINO_KEYSTORE" -storepass "$PASSWORD"
fi

if sudo "$JAVA_HOME/bin/keytool" -list -keystore "$JAVA_HOME/lib/security/cacerts" -storepass "$TRUSTSTORE_PASSWORD" -alias trino >/dev/null 2>&1; then
  echo "Removing existing alias 'trino' from $JAVA_HOME/lib/security/cacerts"
  sudo "$JAVA_HOME/bin/keytool" -delete -alias trino -keystore "$JAVA_HOME/lib/security/cacerts" -storepass "$TRUSTSTORE_PASSWORD"
fi

# create the JKS non-interactively
sudo "$JAVA_HOME/bin/keytool" -genkeypair \
  -alias trino \
  -keyalg RSA -keysize 4096 -validity 3650 \
  -keystore "$TRINO_KEYSTORE" -storetype JKS \
  -storepass "$PASSWORD" -keypass "$PASSWORD" \
  -dname "CN=$(hostname), OU=Trino, O=Acceldata, L=Kitchener, ST=ON, C=CA"

sudo chmod 600 "$TRINO_KEYSTORE"
sudo chown "$TRINO_USER" "$TRINO_KEYSTORE" 2>/dev/null

sudo "$JAVA_HOME/bin/keytool" -exportcert -rfc -alias trino \
  -keystore "$TRINO_KEYSTORE" -storepass "$PASSWORD" \
  -file "$CERT"

sudo "$JAVA_HOME/bin/keytool" -importcert -trustcacerts \
  -keystore "$JAVA_HOME/lib/security/cacerts" -storepass "$TRUSTSTORE_PASSWORD" \
  -alias trino -file "$CERT" -noprompt

if [ -f "$COORDINATOR_CERT" ]; then
  sudo "$JAVA_HOME/bin/keytool" -importcert -trustcacerts \
    -keystore "$JAVA_HOME/lib/security/cacerts" -storepass "$TRUSTSTORE_PASSWORD" \
    -alias trino-coordinator -file "$COORDINATOR_CERT" -noprompt
  sudo rm "$COORDINATOR_CERT" "$CERT"
fi

echo
echo "Your JAVA_HOME is $JAVA_HOME"
echo "Your jks password is $PASSWORD"
echo "Your jks keystore path is $TRINO_KEYSTORE"
cd "$START_DIR"
